swagger: '2.0'
info:
  title: OSU Directory Web API
  description: Web API to search the OSU Online Directory
  version: "1"
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/directory-api
host: localhost
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/Info'
  /directory:
    get:
      tags:
        - directory
      operationId: getByParameters
      description: Get entries in directory filtered by query parameters
      produces:
        - application/json
      parameters:
        - name: firstName
          in: query
          description: First name
          required: false
          type: string
        - name: lastName
          in: query
          description: Last name
          required: false
          type: string
        - name: fullName
          in: query
          description: Full name
          required: false
          type: string
        - name: primaryAffiliation
          in: query
          description: Employee, Student, Other, or Unknown affiliation
          required: false
          type: string
        - name: jobTitle
          in: query
          description: Job title
          required: false
          type: string
        - name: department
          in: query
          description: Department
          required: false
          type: string
        - name: departmentMailingAddress
          in: query
          description: Department mailing address
          required: false
          type: string
        - name: homePhoneNumber
          in: query
          description: Home phone number
          required: false
          type: string
        - name: homeAddress
          in: query
          description: Home address
          required: false
          type: string
        - name: officePhoneNumber
          in: query
          description: Office phone number
          required: false
          type: string
        - name: officeAddress
          in: query
          description: Office address
          required: false
          type: string
        - name: faxNumber
          in: query
          description: Fax number
          required: false
          type: string
        - name: emailAddress
          in: query
          description: Email address
          required: false
          type: string
          format: email
        - name: username
          in: query
          description: User name
          required: false
          type: string
      responses:
        "200":
          description: Array of directory entities
          schema:
            type: array
            items:
              $ref: "#/definitions/directoryEntity"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Error"
      security:
        - directory_api_key: []
  /directory/{osuuid}:
    get:
      tags:
      - directory
      operationId: getByOSUUID
      description: Get entries in directory filtered by query parameters
      parameters:
        - name: osuuid
          in: path
          description: "OSUUID of the person to be fetched."
          type: integer
          format: int64
          required: true
      responses:
        "200":
          description: Directory entity
          schema:
           $ref: "#/definitions/directoryEntity"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: Not found
          schema:
            $ref: "#/definitions/Error"
      security:
        - directory_api_key: []
securityDefinitions:
  directory_api_key:
    type: apiKey
    name: directory_api_key
    in: query
definitions:
  Email:
    type: string
    format: email
  directoryEntity:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      fullName:
        type: string
      primaryAffiliation:
        type: string
      jobTitle:
        type: string
      department:
        type: string
      departmentMailingAddress:
        type: string
      homePhoneNumber:
        type: string
      homeAddress:
        type: string
      officePhoneNumber:
        type: string
      officeAddress:
        type: string
      faxNumber:
        type: string
      emailAddress:
        $ref: "#/definitions/Email"
      username:
        type: string
      osuuid:
        type: integer
        format: int64
  Info:
    properties:
      name:
        type: string
      time:
        type: integer
      commit:
        type: string
      documentation:
        type: string
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
