swagger: '2.0'
info:
  title: OSU Directory Web API
  description: Web API to search the OSU Online Directory
  version: "1"
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/directory-api
host: localhost
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/Info'
  /directory:
    get:
      tags:
        - directory
      operationId: getDirectoryEntries
      description: "Get all entities in directory. Can be filtered by query parameters"
      produces:
        - application/json
      parameters:
        - name: Full Name
          in: query
          description: "Full name of person to be searched for."
          required: false
          type: string
        - name: Surname
          in: query
          description: "Surname of person to be searched for."
          required: false
          type: string
        - name: Email Address
          in: query
          description: "Email address of person to be searched for."
          required: false
          type: string
          format: email
        - name: Office Phone
          in: query
          description: "Office phone number of person to be searched for."
          required: false
          type: string
        - name: Alternate Phone
          in: query
          description: "Alternate phone number of person to be searched for."
          required: false
          type: string
        - name: Home Phone
          in: query
          description: "Home phone number of person to be searched for."
          required: false
          type: string
        - name: Fax Number
          in: query
          description: "Fax number of person to be searched for."
          required: false
          type: string
        - name: Office Address
          in: query
          description: "Office address of person to be searched for."
          required: false
          type: string
        - name: Department
          in: query
          description: "Department of person to be searched for."
          required: false
          type: string
        - name: Affiliation
          in: query
          description: "Any, Employee, Student, Other are valid options to be searched with."
          required: false
          type: string
        - name: Any Phone Number
          in: query
          description: "Any phone number to be searched with"
          required: false
          type: string
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/directoryEntity"
        "400":
          description: "Bad Request"
          #example: "Error: Too many entries returned. Try a more precise search."
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
      security:
        - directory_api_key: []
  /directory/{osuuid}:
    get:
      tags:
      - directory
      operationId: getDirectoryEntryByOsuuid
      parameters:
        - name: osuuid
          in: path
          description: "OSUUID of the person to be fetched."
          type: integer
          format: int64
          required: true
      responses:
        "200":
          description: "Succesful response"
          schema:
           $ref: "#/definitions/directoryEntity"
        "404":
          description: "Resource not found"
        "500":
          description: "Internal server error"
      security:
        - directory_api_key: []
securityDefinitions:
  directory_api_key:
    type: apiKey
    name: directory_api_key
    in: query
definitions:
  Email:
    type: string
    format: email
  directoryEntity:
    required:
      - fullName
      - primaryAffiliation
      - username
    properties:
      firstName:
        type: string
      lastName:
        type: string
      fullName:
        type: string
      primaryAffiliation:
        type: string
      jobTitle:
        type: string
      department:
        type: string
      departmentMailingAddress:
        type: string
      homePhoneNumber:
        type: string
      homeAddress:
        type: string
      officePhoneNumber:
        type: string
      officeAddress:
        type: string
      faxNumber:
        type: string
      emailAddress:
        $ref: "#/definitions/Email"
      username:
        type: string
      osuuid:
        type: integer
        format: int64
  Info:
    properties:
      name:
        type: string
      time:
        type: integer
      commit:
        type: string
      documentation:
        type: string
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
